### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by zerobonx** [NewittAll/modded-palworld-docker-server#2]
stopping at step 18

Step 18/23 : COPY --chown=steam:steam --chmod=755 ./scripts/*.sh /palworld/Scripts
the --chmod option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled

**Comment by NewittAll** [comment]
What version of Docker are you using? Based on the link it sounds like you're using a version older than 23.0, if that is the case try running this:
```shell
DOCKER_BUILDKIT=1 docker build image -t modded-palworld-docker-server .
```

**Comment by zerobonx** [comment]
I use Container Manager (Docker) from Synology -  version 20.10.23-1437

**Comment by zerobonx** [comment]
![image](https://github.com/NewittAll/modded-palworld-docker-server/assets/144956806/f161e84a-fd20-4d70-bcc5-2fe4dc68cec5)

**Comment by NewittAll** [comment]
Try cloning and building the image again, I didn't realize the mods folder got deleted sorry about that.
